name: file_picker_example
description: An example of how to use the file_picker plugin.
version: 1.0.0+2

environment:
  sdk: '>=3.1.0-163.0.dev <4.0.0'
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker:
    path: ../
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true